### ISSUE TITLE
Windows installer link isn't working

### ISSUE THREAD

**Issue by xiaodaigh** [radiant-rstats/docs#1]
https://www.dropbox.com/s/0l6va4pz3s8wghq/Rady-Radiant-Installer-Latest.exe?dl=1

The above link isn't valid and gives 404

**Comment by vnijs** [comment]
I changed the link on the install page a while back. See the install page link and the installer link below.

https://radiant-rstats.github.io/docs/install.html

https://rady.ucsd.edu/faculty/directory/vnijs/Rady-Radiant-Installer-Latest.exe
